server:
  port: 8000
spring:
  main:
    banner-mode: "off"
  redis:
    host: 10.109.252.79
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 500
    database: 0
logging:
  level:
    root: info
    com.ingbyr.hwsc: debug
